### ISSUE TITLE
fava 1.8: AttributeError: 'BufferedWriter' object has no attribute '_write_lock'

### ISSUE THREAD

**Issue by redstreet** [beancount/fava#810]
I upgraded to fava 1.8. I get:

```
Running Fava on http://localhost:5000
AttributeError("'BufferedWriter' object has no attribute '_write_lock'",)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cheroot/server.py", line 1229, in communicate
    req.respond()
  File "/usr/lib/python3.6/site-packages/cheroot/server.py", line 1033, in respond
    self.server.gateway(self).respond()
  File "/usr/lib/python3.6/site-packages/cheroot/wsgi.py", line 147, in respond
    self.write(chunk)
  File "/usr/lib/python3.6/site-packages/cheroot/wsgi.py", line 226, in write
    self.req.ensure_headers_sent()
  File "/usr/lib/python3.6/site-packages/cheroot/server.py", line 1080, in ensure_headers_sent
    self.send_headers()
  File "/usr/lib/python3.6/site-packages/cheroot/server.py", line 1165, in send_headers
    self.conn.wfile.write(EMPTY.join(buf))
  File "/usr/lib/python3.6/site-packages/cheroot/makefile.py", line 29, in write
    with self._write_lock:
AttributeError: 'BufferedWriter' object has no attribute '_write_lock'
AttributeError("'BufferedWriter' object has no attribute '_write_lock'",)
```

I'm running on Cygwin. If I downgrade to 1.7 (via pip), fava works fine. Anyone else seeing this? Apologies if this is specific to me for some reason.

**Comment by yagebu** [comment]
This doesn't seem to have anything to do with Fava, I guess this is a bug with cheroot (or Cygwin).

**Comment by redstreet** [comment]
Yes, it does look like a cheroot bug, perhaps specific to Cygwin, but I posted it here in case others had run into it, given that fava 1.8 is likely exercising some code that exposes this bug, which fava 1.7 doesn't. When I upgrade fava from 1.7 to 1.8 via pip, no other package gets updated, just fava.

Thanks, I'll close this and update this thread if I find out the problem just for everyone's info.

**Comment by yagebu** [comment]
Fava didn't use cheroot before v1.8 btw.

**Comment by jokerjoe** [comment]
Having the same issue running on Cygwin, was wondering if @redstreet you found the problem?

**Comment by JoeTvx** [comment]
Okay, found the problem. _pyio, which is used by cheroot, doesn't work on cygwin because of this:
https://bugs.python.org/issue28459

I applied:
```diff -r 74eb9c51d64e Lib/_pyio.py
--- a/Lib/_pyio.py	Thu Oct 20 16:33:39 2016 -0400
+++ b/Lib/_pyio.py	Fri Oct 21 06:38:50 2016 +0900
@@ -13,8 +13,13 @@
     from _thread import allocate_lock as Lock
 except ImportError:
     from _dummy_thread import allocate_lock as Lock
-if sys.platform in {'win32', 'cygwin'}:
+if sys.platform == 'win32':
     from msvcrt import setmode as _setmode
+elif sys.platform == 'cygwin':
+    import ctypes
+    _cygwin1 = ctypes.PyDLL('cygwin1.dll')
+    def _setmode(fd, mode):
+        return _cygwin1._setmode(ctypes.c_int(fd), ctypes.c_int(mode))
 else:
     _setmode = None```

from:
https://bugs.python.org/file45163/cygwin-pyio-setmode.patch

Beancount works now. I didn't apply the rest of the patch above (to ctypes, distutils), and haven't investigated to see if this is an issue. So use at your own risk.

**Comment by redstreet** [comment]
Okay, found the problem. _pyio, which is used by cheroot, doesn't work on cygwin because of this:
https://bugs.python.org/issue28459

I applied:
```
diff -r 74eb9c51d64e Lib/_pyio.py
--- a/Lib/_pyio.py	Thu Oct 20 16:33:39 2016 -0400
+++ b/Lib/_pyio.py	Fri Oct 21 06:38:50 2016 +0900
@@ -13,8 +13,13 @@
     from _thread import allocate_lock as Lock
 except ImportError:
     from _dummy_thread import allocate_lock as Lock
-if sys.platform in {'win32', 'cygwin'}:
+if sys.platform == 'win32':
     from msvcrt import setmode as _setmode
+elif sys.platform == 'cygwin':
+    import ctypes
+    _cygwin1 = ctypes.PyDLL('cygwin1.dll')
+    def _setmode(fd, mode):
+        return _cygwin1._setmode(ctypes.c_int(fd), ctypes.c_int(mode))
 else:
     _setmode = None
```

from:
https://bugs.python.org/file45163/cygwin-pyio-setmode.patch

Beancount works now. I didn't apply the rest of the patch above (to ctypes, distutils), and haven't investigated to see if this is an issue. So use at your own risk.

**Comment by Shadowhandler** [comment]
I get the problem too.seem like not stable in cygwin.So backward to 1.7v.

**Comment by Shadowhandler** [comment]
So,nobody fix the problem?
